ACL Calculation added to scraper
flipkart-incubator/ottoscalr pull request #12
Opened 2023-04-26 12:08 UTC by deefreak

Implementation of ACL Calculation.
The PodBootstrap time fetching query is (Pod Ready Time - Pod Created Time). Have taken minimum of all the pods for a workload currently. 
Test is also written.

2023-04-27 06:00 UTC, neerajb requested changes

2023-04-27 06:00 UTC, neerajb commented on pkg/metrics/scraper.go
> +	podBootstrapTime, err := strconv.ParseFloat(strings.Split(strings.Split(result.String(), "=> ")[1], " @")[0], 32)
Why are we reading the result as a string. Please use the appropriate type from github.com/prometheus/common/model package. Do not deserialize it manually.

2023-04-27 07:40 UTC, deefreak commented on pkg/metrics/scraper.go
> +const MetricIngestionTime = 15.0
Done

2023-04-28 05:41 UTC, neerajb approved these changes

2023-04-28 05:41 UTC, merged